### ISSUE TITLE
Issue on running the server

### ISSUE THREAD

**Issue by raminbp** [apple/ccs-calendarserver#468] opened 2016-10-11 16:01 UTC
executing bin/run gives following: 

python: posix_spawn: /my-path/ccs-calendarserver/.develop/virtualenv/bin/python2.72.7: No such file or directory

platform: Mac Osx El capitan

**Comment by dreness** [comment] 2016-10-11 21:50
Hi @raminbp 

Your error looks similar to what happens if pip is not installed. Until just a moment ago, the README was incorrect in its reference to using bin/install_pip, as we no longer ship such a script. I've updated [README.rst](README.rst) to add the instruction to run "python -m ensurepip" to install pip, if you don't have it already.

Also, I feel like there might be issues with the keychain integration (specific to OS X). I haven't nailed it down yet, but it doesn't seem particularly happy right now on a couple different test machines. You can bypass the keychain integration by running: export USE_OPENSSL=1 prior to running ./bin/develop. If you have already run ./bin/develop, delete the .develop directory, then set USE_OPENSSL and run ./bin/develop again.

Update: the keychain weirdness is that if there are any mis-steps at all (such as, for example, attempting the bootstrapping over SSH, which prevents the GUI credential prompt from keychain, you have to purge as many of the following things from keychain as exist: the 'localhost' cert, the 'Imported Private Key', and the 'org.calendarserver.test' identity preference. THEN REBOOT before retrying, due to a securityd caching issue.

**Comment by raminbp** [comment] 2016-10-12 05:24
Hi @dreness 

I noticed the bin/install_pip doesn't exist but as far i saw in the logs , pip is installed during the first execution of bin/run. I also installed pip using the brew and the result was the same.  i'll try your solution see if it resolves. 

Thank you

**Comment by raminbp** [comment] 2016-10-12 08:57
here is the last lines of running run/develop with use_openssl = 1

...

Installing collected packages: setuptools
Successfully installed setuptools-23.1.0

---

Installing pip==8.1.2
Collecting pip==8.1.2
  Using cached pip-8.1.2-py2.py3-none-any.whl
Installing collected packages: pip
Successfully installed pip-8.1.2

---

Installing virtualenv==15.0.2
Collecting virtualenv==15.0.2
  Using cached virtualenv-15.0.2-py2.py3-none-any.whl
Installing collected packages: virtualenv
Successfully installed virtualenv-15.0.2
New python executable in /Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/virtualenv/bin/python2.7
Also creating executable in /Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/virtualenv/bin/python
Installing pip, wheel...done.
macOS virtualenv codesign fix.
python: posix_spawn: /Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/virtualenv/bin/python2.72.7: No such file or directory

**Comment by dreness** [comment] 2016-10-12 18:38
@raminbp Hrm, with a closer look at your original message I might have noticed that it's trying to access "python2.72.7", which is understandably not present.

I'd guess something about your setup violates the assumptions of CalendarServer's run / setup scripts. To get some debug information, try editing bin/_build.sh to add "set -x" right above the line '. "${wd}/bin/_py.sh";', then run ./bin/develop again. If you can share the output of that, hopefully I can figure out what's going on. The first part of the output should document how these scripts find a suitable python to use. On my system, the output is:

```
++ . /Users/andre/work/server/ccs-calendarserver/bin/_py.sh
+ develop
+ init_build
+ cd /Users/andre/work/server/ccs-calendarserver
+ init_py
++ detect_python_version
++ local v
++ local p
++ for v in '"2.7"' '""'
++ for p in '"${PYTHON:=}"' '"python${v}"'
+++ find_cmd ''
+++ local cmd=
+++ shift
++++ type ''
++++ sed 's|^ is \(a tracked alias for \)\{0,1\}||'
+++ local path=
+++ '[' -z '' ']'
+++ return 1
++ p=
++ for p in '"${PYTHON:=}"' '"python${v}"'
+++ find_cmd python2.7
+++ local cmd=python2.7
+++ shift
++++ type python2.7
++++ sed 's|^python2.7 is \(a tracked alias for \)\{0,1\}||'
+++ local path=/usr/bin/python2.7
+++ '[' -z /usr/bin/python2.7 ']'
+++ echo /usr/bin/python2.7
++ p=/usr/bin/python2.7
++ try_python /usr/bin/python2.7
++ local python=/usr/bin/python2.7
++ shift
++ '[' -z /usr/bin/python2.7 ']'
++ type /usr/bin/python2.7
+++ py_version /usr/bin/python2.7
+++ local python=/usr/bin/python2.7
+++ shift
++++ /usr/bin/python2.7 -c 'from distutils.sysconfig import get_python_version; print get_python_version()'
+++ echo 2.7
++ local py_version=2.7
+++ echo 2.7
+++ sed 's|\.||'
++ '[' 27 -lt 25 ']'
++ return 0
++ echo /usr/bin/python2.7
++ return 0
+ bootstrap_python=/usr/bin/python2.7
++ find_cmd /usr/bin/python2.7
++ local cmd=/usr/bin/python2.7
++ shift
+++ type /usr/bin/python2.7
+++ sed 's|^/usr/bin/python2.7 is \(a tracked alias for \)\{0,1\}||'
++ local path=/usr/bin/python2.7
++ '[' -z /usr/bin/python2.7 ']'
++ echo /usr/bin/python2.7
+ export PYTHON=/usr/bin/python2.7
+ PYTHON=/usr/bin/python2.7
```

**Comment by raminbp** [comment] 2016-10-12 19:18
- cd /Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver
- py_dependencies
- python=/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/virtualenv/bin/python
- py_ve_tools=/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/ve_tools
- export PATH=/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/virtualenv/bin:/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/roots/PostgreSQL/bin:/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/roots/memcached/bin:/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/roots/libevent/bin:/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/roots/openssl/bin:/Users/raminbpr/bin/mongodb-osx-x86_64-3.0.6/bin:/Users/raminbpr/bin/Sencha/Cmd/6.1.3.42/..:/Users/raminbpr/bin/Sencha/Cmd/6.0.2.14/..:/Users/raminbpr/Projects/Personal/depot-tools:/Users/raminbpr/bin/Sencha/Cmd/6.0.2.14/..:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
- PATH=/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/virtualenv/bin:/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/roots/PostgreSQL/bin:/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/roots/memcached/bin:/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/roots/libevent/bin:/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/roots/openssl/bin:/Users/raminbpr/bin/mongodb-osx-x86_64-3.0.6/bin:/Users/raminbpr/bin/Sencha/Cmd/6.1.3.42/..:/Users/raminbpr/bin/Sencha/Cmd/6.0.2.14/..:/Users/raminbpr/Projects/Personal/depot-tools:/Users/raminbpr/bin/Sencha/Cmd/6.0.2.14/..:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
- export PYTHON=/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/virtualenv/bin/python
- PYTHON=/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/virtualenv/bin/python
- export PYTHONPATH=/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/ve_tools/lib:/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver:
- PYTHONPATH=/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/ve_tools/lib:/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver:
- mkdir -p /Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/patches
  ++ uname -s
- '[' Darwin = Darwin ']'
- /usr/local/Cellar/python/2.7.12_2/bin/python2.7 -c 'import distutils.sysconfig; print distutils.sysconfig.get_config_var("CFLAGS")'
- grep -e -mno-fused-madd
- true
- false
- '[' '!' -d /Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/virtualenv ']'
- bootstrap_virtualenv
- mkdir -p /Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/ve_tools
- export PYTHONUSERBASE=/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/ve_tools
- PYTHONUSERBASE=/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/ve_tools
- for pkg in setuptools==18.5 pip==8.1.2 virtualenv==15.0.2
- ruler 'Installing setuptools==18.5'
- true
- echo ____________________________________________________________
- echo ''
- '[' 1 -gt 0 ']'
- echo 'Installing setuptools==18.5'
- /usr/local/Cellar/python/2.7.12_2/bin/python2.7 -m pip install -I --user setuptools==18.5
- for pkg in setuptools==18.5 pip==8.1.2 virtualenv==15.0.2
- ruler 'Installing pip==8.1.2'
- true
- echo ____________________________________________________________
- echo ''
- '[' 1 -gt 0 ']'
- echo 'Installing pip==8.1.2'
- /usr/local/Cellar/python/2.7.12_2/bin/python2.7 -m pip install -I --user pip==8.1.2
- for pkg in setuptools==18.5 pip==8.1.2 virtualenv==15.0.2
- ruler 'Installing virtualenv==15.0.2'
- true
- echo ____________________________________________________________
- echo ''
- '[' 1 -gt 0 ']'
- echo 'Installing virtualenv==15.0.2'
- /usr/local/Cellar/python/2.7.12_2/bin/python2.7 -m pip install -I --user virtualenv==15.0.2
- /usr/local/Cellar/python/2.7.12_2/bin/python2.7 -m virtualenv --system-site-packages --no-setuptools /Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/virtualenv
- case "$(uname -s)" in
  ++ uname -s
- echo 'macOS virtualenv codesign fix.'
- cp /usr/bin/python /Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/virtualenv/bin/python
- cd /Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver
- PYTHONPATH=/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/ve_tools/lib:/Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver:
- /Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/.develop/virtualenv/bin/python /Users/raminbpr/Projects/Gam/darwin/ccs-calendarserver/setup.py check

**Comment by raminbp** [comment] 2016-10-12 19:40
it doesn't look like your output

**Comment by dreness** [comment] 2016-10-12 20:59
Apparently this is somehow related to using python from homebrew. In a fresh VM, I installed dev tools, homebrew, ran "brew install python", and then git cloned the CS repo, which fails with the same error message you posted:

`python: posix_spawn: /Users/local/ccs-calendarserver/.develop/virtualenv/bin/python2.72.7: No such file or directory`

I'll investigate...

**Comment by raminbp** [comment] 2016-10-12 21:04
thank you very much

**Comment by dreness** [comment] 2016-10-12 22:04
@raminbp This seems to be caused by something we do during setup that's really only intended for the Server.app distribution of Calendar Server, related to code signing and other things that hopefully are of no interest to anyone reading this. We shouldn't be doing our 'codesign fix' for this, the open source distribution, and I will be confining that behavior to Server.app builds momentarily. In the mean time, if you comment out the 'cp' command shown below, that should fix it for you:

```
diff --git a/bin/_build.sh b/bin/_build.sh
index e3ec9b7..e6baed4 100644
--- a/bin/_build.sh
+++ b/bin/_build.sh
@@ -661,8 +661,8 @@ py_dependencies () {
       "${py_virtualenv}";
     case "$(uname -s)" in
       Darwin)
-        echo "macOS virtualenv codesign fix."
-        cp "/usr/bin/python" "${py_bindir}/python";
+        echo "skipping macOS virtualenv codesign fix."
+        #cp "/usr/bin/python" "${py_bindir}/python";
         ;;
     esac;
   fi;
```

... or you can just wait until I push a fix for this, which should be coming soon...

**Comment by dreness** [comment] 2016-10-12 23:48
@raminbp This should be fixed as of https://github.com/apple/ccs-calendarserver/commit/935cf46edc39e17d163af796f9793c7600f6e837. You should delete the .develop directory before retrying, and you might even have to do the silly stuff I mentioned in the Update to this comment: https://github.com/apple/ccs-calendarserver/issues/468#issuecomment-253057362

**Comment by raminbp** [comment] 2016-10-13 05:21
@dreness thank you very much, now its working

**Comment by dreness** [comment] 2016-10-13 16:01
@raminbp you're welcome! glad to hear it's working. Perhaps I will add some automated tests that use other pythons... all our automated tests on OS X use apple's Python.

**Closed as completed by dreness** 2016-10-13 16:01 UTC
